### ISSUE TITLE
Caddy instead of ingress

### ISSUE THREAD

**Issue by Zhomart** [CommercialTribe/psykube#35]
I like ingress, but it doesn't feel like production ready yet. GCP's ingress controllers have quotas, nginx controller still beta and have issues. 

What do you think about adding [Caddy](https://caddyserver.com/) as a proxy server? 
It has easy https supports, automatic certificate update from letsencrypt and more.

**Comment by jwaldrip** [comment]
Shouldn't really matter. Psykube doesn't know of ingress controllers. It just knows to create the ingress records. You could create your own controller using caddy no?

**Comment by Zhomart** [comment]
You're right. What I was thinking is creating a psykube DSL that creates Caddy load-balancer.
Example

```yaml
name: test-app
registry_user: commercial-tribe
ports:
  http: 80
proxy: # creates caddy load-balancer
  tls: true
  address: "11.1.1.1"
```
